Flownative:
  Canto:
    mapping:
      # map "Custom Fields" from Canto to Neos
      customFields: []
#      customFields:
#        # Foo Bar Baz                    # the name in Canto, for readbility
#        'meta_multichoice_0':            # the custom field id in Canto
#          asAssetCollection: false       # map to an asset collection named after the field
#          valuesAsTags: false            # map field values to Neos tags; if true an asset is assigned a tag corresponding to the value, if false any asset "having the field" is in the collection
#          include: []                    # only include the listed field values as tags
#          exclude: []                    # exclude the listed field values as tags
Neos:
  Flow:
    mvc:
      routes:
        'Flownative.Canto':
          position: 'start'

    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Flownative.Canto:AuthorizationController':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'Flownative\Canto\Controller\AuthorizationController'

  Media:
    assetSources:
      'flownative-canto':
        assetSource: 'Flownative\Canto\AssetSource\CantoAssetSource'
        assetSourceOptions:
          iconPath: 'resource://Flownative.Canto/Public/Icons/Canto-Logo-White.svg'
          description: 'Assets in Canto Digital Asset Management'
          appId: '%env:FLOWNATIVE_CANTO_OAUTH_APP_ID%'
          appSecret: '%env:FLOWNATIVE_CANTO_OAUTH_APP_SECRET%'
          apiBaseUri: '%env:FLOWNATIVE_CANTO_API_BASE_URI%'

  Neos:
    modules:
      management:
        submodules:
          canto:
            controller: 'Flownative\Canto\Controller\CantoController'
            label: 'Canto'
            description: 'Flownative.Canto:Main:moduleDescription'
            icon: 'fas fa-photo-video'
            privilegeTarget: 'Flownative.Canto:ManageConnection'
